<?php

namespace JustCoded\WP\Framework\Supports;

use jcf\models\Settings;
use JustCoded\WP\Framework\Objects\Singleton;

/**
 * Class Just_Custom_Fields
 *
 * Register hooks to rewrite storage file path
 *
 * @package JustCoded\WP\Framework\Supports
 */
class Just_Custom_Fields {
	use Singleton;

	/**
	 * Just_Custom_Fields constructor.
	 * Register jcf hooks
	 */
	protected function __construct() {
		add_filter( 'jcf_config_filepath', array( $this, 'jcf_config_filepath' ), 10, 2 );
	}

	/**
	 * Patch config file path to get data from "/config/jcf.json" file
	 *
	 * @param string $path  Path generated by a plugin.
	 * @param string $source_settings   Source settings value.
	 *
	 * @return string
	 */
	public function jcf_config_filepath( $path, $source_settings ) {
		if ( Settings::CONF_SOURCE_FS_THEME === $source_settings ) {
			$path = get_stylesheet_directory() . '/config/just-custom-fields.json';
		}
		return $path;
	}
}
